name: Build & Deploy docs (docToolchain)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build docs with docToolchain (SDKMAN)
        shell: bash
        run: |
          set -e

          # Preflight: Quellen + Config vorhanden?
          test -f docs/arc42/arc42.adoc || { echo "Fehlt: docs/arc42/arc42.adoc"; exit 1; }
          test -f docToolchainConfig.groovy || { echo "Fehlt: docToolchainConfig.groovy im Repo-Root"; exit 1; }
          grep -q "inputFiles" docToolchainConfig.groovy || { echo "In docToolchainConfig.groovy fehlt 'inputFiles'"; exit 1; }

          # SDKMAN + docToolchain in DIESEM Step installieren und initialisieren
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install doctoolchain

          # Build
          doctoolchain . generateHTML

          # Ergebnis prüfen und für Pages bereitstellen
          test -f build/html/index.html || { echo "Build hat keine build/html/index.html erzeugt"; exit 1; }
          rm -rf _site && mkdir -p _site
          cp -a build/html/. _site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4