# .github/workflows/gh-pages.yml
name: Deploy Docs to GitHub Pages (docToolchain via SDKMAN)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java (for docToolchain)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Build docs (docToolchain via SDKMAN)
        shell: bash
        run: |
          set -e
          # Install SDKMAN + docToolchain
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install doctoolchain

          # Expect: docs/arc42/arc42.adoc exists
          if [ ! -f docs/arc42/arc42.adoc ]; then
            echo "Missing docs/arc42/arc42.adoc"; exit 1
          fi

          # Minimal Config.groovy for CI
          cat > Config.groovy <<'EOF'
          inputPath  = 'docs/arc42'
          outputPath = 'build'
          asciidoc = [
            inputFiles: ['arc42.adoc']
          ]
          EOF

          echo "Using Config.groovy:"
          cat Config.groovy

          # Build HTML
          doctoolchain "$PWD" generateHTML

          # Prepare artifact for Pages
          rm -rf _site && mkdir -p _site
          cp -a build/html/. _site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4